## Problem Statement:

Given a input of sudoko cells in consecutive order as a single string, with `0` denoting an empty cell, construct the solved sudoku board.

Notes:
- the sudoku board will always be size 9x9

A sample input would be: '630000000000500000000000000000000000000000000000000000000000000000000000000000000'

In [1]:
from typing import Tuple
import numpy as np

<img src="images/sudoku_board.png" width="200"/>

In [2]:
def get_box_vals(board, row: int, col: int) -> list:
    ''' get 3x3 box values from top left corner '''
    row_start, col_start = row//3 * 3, col//3 * 3
    
    return board[row_start:row_start+3, col_start:col_start+3]

In [3]:
def solve(board) -> Tuple[bool, list]:
    for i in range(9):  # row
        for j in range(9):  # col
            if board[i][j] == 0:  # only consider empty values
                # consider values [1,9] that aren't in row, col, or box
                possible_vals = [x for x in range(1,10) if 
                                 (x not in board[i]) and  # row_vals
                                 (x not in board[:, j]) and  # col_vals
                                 (x not in get_box_vals(board, i, j))  # box_vals
                                ]
                
                # construct board with each value recursively
                for val in possible_vals:
#                     print(f'[{i}, {j}]: {val} -- {possible_vals}')
                    board[i][j] = val
                    if solve(board)[0]:
                        return True, board  # board is solved
                    else:
                        board[i][j] = 0  # board couldn't be solved, reset to 0
                
                return False, board  # board couldn't be solved for any possible values
    
    return True, board  # board is solved

In [4]:
input_ = '361025900080960000000000000000000000000000000000000000000000000000000000000000000'
board_unsolved = np.reshape(list(map(int, input_)), (9,9))
print(board_unsolved, '\n{}'.format('-' * 20))

solved, board_solved = solve(board_unsolved)

if solved: print(board_solved)

[[3 6 1 0 2 5 9 0 0]
 [0 8 0 9 6 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]] 
--------------------
[[3 6 1 4 2 5 9 7 8]
 [2 8 4 9 6 7 1 3 5]
 [5 7 9 1 3 8 2 4 6]
 [1 2 3 5 4 6 7 8 9]
 [4 5 6 7 8 9 3 1 2]
 [7 9 8 2 1 3 5 6 4]
 [6 1 2 3 5 4 8 9 7]
 [8 3 7 6 9 2 4 5 1]
 [9 4 5 8 7 1 6 2 3]]
